name: Asset Quality Workflow

on: [push, pull_request]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run npm install
      working-directory: ./util
      run: |
        npm install

    # The 'check' will verify the contents of the 'metadata.json'
    # file of all assets (including newly added ones).
    - name: Run npm check
      working-directory: ./util
      run: |
        npm run check

    # The 'update' will create the REUSE.toml file, which is
    # required for the subsequent REUSE compliance check.
    - name: Run npm update
      working-directory: ./util
      run: |
        npm run update

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v6
