name: Asset Quality Workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Checkout PR
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh pr checkout ${{ github.event.pull_request.number }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: latest

    - name: Execute PHP script
      run: |
        php util/model.php --no-warn --check --update --process-repo --verbose

    - name: Commit list of files back into the repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: |
        git add --verbose .
        git diff-index  HEAD || git commit -m "Updating generated Repo indices"
        git push