name: Asset Quality Workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Checkout PR
      run: gh pr checkout ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: latest

    - name: Execute PHP script
      run: |
        php util/model.php --no-warn --check --update --process-repo --verbose

    - name: Commit list of files back into the repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add --verbose .
        git diff-index  HEAD || git commit -m "Updating generated Repo indices"
        git push