name: Asset Quality Workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
        ref: ${{ github.head_ref }}

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: latest

    - name: Execute PHP script
      run: |
        php util/model.php --no-warn --check --update --process-repo --verbose

    - name: Commit list of files back into the repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Updating generated Repo indices
