name: Rebuild All Model Assets

# Only need to handle pushes to 'main' because merged PRs do that
# along with direct pushes. 
on: 
  push:
    branches:
      - 'main'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: latest

    - name: Execute PHP script to update Repo
      run: |
        php util/model.php --no-warn --update --process-repo

    - name: Commit changes to a new branch 
      uses: EndBug/add-and-commit@v9
      with:
        # Defaults for most parameters are used
        # Action assiged to "github_actor" (used by default with 'default_author')
        # This action merges all changes into 'main'

        # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
        # - ignore -> errors will be logged but the step won't fail
        # - exitImmediately -> the action will stop right away, and the step will fail
        # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
        # Default: ignore
        pathspec_error_handling: exitAtEnd

